/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ldtteam.tableau.neogradle;

import com.ldtteam.tableau.extensions.NeoGradleExtension;
import net.neoforged.gradle.userdev.UserDevPlugin;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.jetbrains.annotations.NotNull;

public class NeoGradleProjectPlugin implements Plugin<Project> {

    @Override
    public void apply(@NotNull Project target) {
        target.getPlugins().apply(UserDevPlugin.class);

        target.getExtensions().create(NeoGradleExtension.EXTENSION_NAME, NeoGradleExtension.class, target);
    }
}
