/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ldtteam.tableau.sonarqube;

import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.jetbrains.annotations.NotNull;

public class SonarqubeProjectPlugin implements Plugin<Project> {

    @Override
    public void apply(@NotNull Project target) {
        //TODO: Implement this method
    }
}
