/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ldtteam.tableau.resource.processing;

import com.ldtteam.tableau.resource.processing.extensions.ResourceProcessingExtension;
import com.ldtteam.tableau.scripting.extensions.TableauScriptingExtension;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.jetbrains.annotations.NotNull;

public class ResourceProcessingProjectPlugin implements Plugin<Project> {

    @Override
    public void apply(@NotNull Project target) {
        TableauScriptingExtension.register(target, ResourceProcessingExtension.EXTENSION_NAME, ResourceProcessingExtension.class, target);
    }
}
