/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ldtteam.tableau.git;

import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.jetbrains.annotations.NotNull;

import javax.inject.Inject;

/**
 * The root plugin for the Git module.
 * <p>
 *     Can be applied to any {@link org.gradle.api.plugins.PluginAware} but will only interact with {@link Project projects}
 */
public class GitPlugin implements Plugin<Object> {

    /**
     * Creates a new plugin instance.
     */
    @Inject
    public GitPlugin() {
    }

    @Override
    public void apply(@NotNull Object target) {
        if (target instanceof Project project) {
            project.getPlugins().apply(GitProjectPlugin.class);
        }
    }
}
