/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ldtteam.tableau.git;

import com.ldtteam.tableau.git.extensions.GitExtension;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.jetbrains.annotations.NotNull;

public class GitProjectPlugin implements Plugin<Project> {

    @Override
    public void apply(@NotNull Project target) {
        target.getExtensions().create(GitExtension.EXTENSION_NAME, GitExtension.class, target);
    }
}
