/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ldtteam.tableau.git;

import com.ldtteam.tableau.git.extensions.GitExtension;
import com.ldtteam.tableau.scripting.extensions.TableauScriptingExtension;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.jetbrains.annotations.NotNull;

import javax.inject.Inject;

/**
 * Module plugin for Git, configures to extract information from its git repository.
 */
public class GitProjectPlugin implements Plugin<Project> {

    /**
     * Creates a new plugin instance.
     */
    @Inject
    public GitProjectPlugin() {
    }

    @Override
    public void apply(@NotNull Project target) {
        TableauScriptingExtension.register(target, GitExtension.EXTENSION_NAME, GitExtension.class, target);
    }
}
