/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ldtteam.tableau.sourceset.management;

import com.ldtteam.tableau.scripting.extensions.TableauScriptingExtension;
import com.ldtteam.tableau.sourceset.management.extensions.SourceSetExtension;
import com.ldtteam.tableau.utilities.extensions.UtilityFunctions;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.artifacts.Configuration;
import org.gradle.api.artifacts.Dependency;
import org.gradle.api.plugins.JavaPluginExtension;
import org.gradle.api.tasks.SourceSet;
import org.gradle.api.tasks.SourceSetContainer;
import org.jetbrains.annotations.NotNull;

import java.util.*;

public class SourcesetManagementProjectPlugin implements Plugin<Project> {

    @Override
    public void apply(@NotNull Project target) {
        TableauScriptingExtension.register(target, SourceSetExtension.EXTENSION_NAME, SourceSetExtension.class, target);
        configureMainSourceSet(target);
    }

    private static void configureMainSourceSet(@NotNull Project target) {
        final JavaPluginExtension java = target.getExtensions().getByType(JavaPluginExtension.class);
        java.withSourcesJar();
        java.withJavadocJar();
    }
}
