package com.ldtteam.tableau.neoforge.metadata.components;

import com.electronwill.nightconfig.core.CommentedConfig;
import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class HeaderComponentTest {

    private HeaderComponent headerComponent;

    @BeforeEach
    void setUp() {
        Project project = ProjectBuilder.builder().build();
        headerComponent = project.getObjects().newInstance(HeaderComponent.class);
    }

    @Test
    void testInitialization() {
        assertNotNull(headerComponent);
    }

    @Test
    void testWrite() {
        CommentedConfig config = CommentedConfig.inMemory();
        headerComponent.write(config);

        String expectedHeader = """
            NeoForge Mod Metadata file.
            This file is generated by Tableau.
            Any changes you make to it in a Tableau workspace will be overriden.
            """;

        assertEquals(expectedHeader, config.getComment(""));
    }
}