/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ldtteam.tableau.parchment;

import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.jetbrains.annotations.NotNull;

public class ParchmentProjectPlugin implements Plugin<Project> {

    @Override
    public void apply(@NotNull Project target) {
        throw new IllegalStateException("Not implemented yet");
    }
}
