/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ldtteam.tableau.module-template-packagetree;

import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.jetbrains.annotations.NotNull;

import javax.inject.Inject;

/**
 * Module Plugin for handling ModuleTemplate.
 * <p>
 *     Can be applied to any {@link org.gradle.api.plugins.PluginAware} but will only operate on
 *     {@link Project projects}
 */
public class ModuleTemplatePlugin implements Plugin<Object> {

    /**
     * Creates a new plugin instance.
     */
    @Inject
    public ModuleTemplatePlugin() {
    }

    @Override
    public void apply(@NotNull Object target) {
        if (target instanceof Project project) {
            project.getPlugins().apply(ModuleTemplateProjectPlugin.class);
        }
    }
}
