/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ldtteam.tableau.utilities;

import com.ldtteam.tableau.scripting.extensions.TableauScriptingExtension;
import com.ldtteam.tableau.utilities.extensions.UtilityFunctions;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.jetbrains.annotations.NotNull;

import javax.inject.Inject;

/**
 * Project plugin for the utilities module.
 * <p>
 *     Configures the project with the utility functions.
 */
public class UtilitiesProjectPlugin implements Plugin<Project> {

    /**
     * Creates a new plugin instance.
     */
    @Inject
    public UtilitiesProjectPlugin() {
    }

    @Override
    public void apply(@NotNull Project target) {
        TableauScriptingExtension.register(target, UtilityFunctions.EXTENSION_NAME, UtilityFunctions.class);
    }
}
