/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ldtteam.tableau.dependencies;

import com.ldtteam.tableau.dependencies.extensions.DependenciesExtension;
import com.ldtteam.tableau.scripting.extensions.TableauScriptingExtension;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.plugins.JavaLibraryPlugin;
import org.jetbrains.annotations.NotNull;

public class DependenciesProjectPlugin implements Plugin<Project> {

    @Override
    public void apply(@NotNull Project target) {
        target.getPlugins().apply(JavaLibraryPlugin.class);
        TableauScriptingExtension.register(target, DependenciesExtension.EXTENSION_NAME, DependenciesExtension.class, target);
    }
}
