/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ldtteam.tableau.java;

import com.ldtteam.tableau.java.extensions.JavaExtension;
import com.ldtteam.tableau.scripting.extensions.TableauScriptingExtension;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.jetbrains.annotations.NotNull;

public class JavaProjectPlugin implements Plugin<Project> {

    @Override
    public void apply(@NotNull Project target) {
        target.getPlugins().apply("java-library");

        TableauScriptingExtension.register(target, JavaExtension.EXTENSION_NAME, JavaExtension.class, target);
    }
}
