/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ldtteam.tableau.scripting;

import com.ldtteam.tableau.scripting.extensions.TableauScriptingExtension;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.jetbrains.annotations.NotNull;

import javax.inject.Inject;

/**
 * Core scripting logic plugin for projects.
 * Allows for an extensible scripting extension as the root for our DSL.
 */
public class ScriptingProjectPlugin implements Plugin<Project> {

    /**
     * Creates a new instance of the plugin.
     */
    @Inject
    public ScriptingProjectPlugin() {
    }

    @Override
    public void apply(@NotNull Project target) {
        target.getExtensions().create(TableauScriptingExtension.EXTENSION_NAME, TableauScriptingExtension.class);
    }
}
