/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ldtteam.tableau.scripting;

import com.ldtteam.tableau.scripting.extensions.TableauScriptingExtension;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.jetbrains.annotations.NotNull;

public class ScriptingProjectPlugin implements Plugin<Project> {

    @Override
    public void apply(@NotNull Project target) {
        target.getExtensions().create(TableauScriptingExtension.EXTENSION_NAME, TableauScriptingExtension.class);
    }
}
