/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ldtteam.tableau.maven.publishing;

import com.ldtteam.tableau.common.CommonPlugin;
import com.ldtteam.tableau.git.GitPlugin;
import com.ldtteam.tableau.scripting.extensions.TableauScriptingExtension;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.publish.PublishingExtension;
import org.gradle.api.publish.maven.MavenPublication;
import org.gradle.api.publish.maven.plugins.MavenPublishPlugin;
import org.jetbrains.annotations.NotNull;

public class MavenPublishingProjectPlugin implements Plugin<Project> {

    @Override
    public void apply(@NotNull Project target) {
        target.getPlugins().apply("maven-publish");
        target.getPlugins().apply(CommonPlugin.class);
        target.getPlugins().apply(GitPlugin.class);

        TableauScriptingExtension.register(target, MavenPublishingExtension.EXTENSION_NAME, MavenPublishingExtension.class, target);
    }

    public void configurePublication(Project project) {
        final PublishingExtension publishing = project.getExtensions().getByType(PublishingExtension.class);
        final MavenPublishingExtension mavenPublishing = MavenPublishingExtension.get(project);

        publishing.getPublications().create("default", MavenPublication.class, publication -> {
            publication.from(project.getComponents().getByName("java"));
            publication.pom(mavenPublishing::configure);
            publication.suppressAllPomMetadataWarnings();
        });
    }
}
