/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ldtteam.tableau.maven.publishing;

import com.ldtteam.tableau.common.CommonPlugin;
import com.ldtteam.tableau.git.GitPlugin;
import com.ldtteam.tableau.scripting.extensions.TableauScriptingExtension;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.publish.PublishingExtension;
import org.gradle.api.publish.maven.MavenPublication;
import org.gradle.api.publish.maven.plugins.MavenPublishPlugin;
import org.jetbrains.annotations.NotNull;

import javax.inject.Inject;

/**
 * Maven publishing project plugin.
 * <p>
 *     Configures a projects maven publishing system.
 *     Can read information from the git module, or from the common module.
 */
public class MavenPublishingProjectPlugin implements Plugin<Project> {

    /**
     * Creates a new plugin instance.
     */
    @Inject
    public MavenPublishingProjectPlugin() {
    }

    @Override
    public void apply(@NotNull Project target) {
        target.getPlugins().apply("maven-publish");
        target.getPlugins().apply(CommonPlugin.class);
        target.getPlugins().apply(GitPlugin.class);

        TableauScriptingExtension.register(target, MavenPublishingExtension.EXTENSION_NAME, MavenPublishingExtension.class, target);

        configurePublication(target);
    }

    /**
     * Configures the publication of the project.
     *
     * @param project The project to configure.
     */
    private void configurePublication(Project project) {
        final PublishingExtension publishing = project.getExtensions().getByType(PublishingExtension.class);
        final MavenPublishingExtension mavenPublishing = MavenPublishingExtension.get(project);

        project.afterEvaluate(ignored -> {
            //This needs to be in an after evaluate block to ensure that the project has been configured.
            publishing.getPublications().create("default", MavenPublication.class, publication -> {
                publication.from(project.getComponents().getByName("java"));
                publication.pom(mavenPublishing::configure);
                publication.suppressAllPomMetadataWarnings();
            });
        });
    }
}
