/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ldtteam.tableau.changelog;

import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.jetbrains.annotations.NotNull;

import javax.inject.Inject;

/**
 * Module plugin for the changelog module
 * <p>
 *     Can be applied to any {@link org.gradle.api.plugins.PluginAware} but will
 *     only operate on {@link Project projects}.
 */
public class ChangelogPlugin implements Plugin<Object> {

    /**
     * Creates a new plugin instance.
     */
    @Inject
    public ChangelogPlugin() {
    }

    @Override
    public void apply(@NotNull Object target) {
        if (target instanceof Project project) {
            project.getPlugins().apply(ChangelogProjectPlugin.class);
        }
    }
}
